# Default values for otus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: otus
image: 
    name: ledzhy/otus6
    tag: latest
replicaCount: 1
network:
    protocol: TCP
    type: NodePort
    port: 8000
    alias: arch.homework
health:
    path: /health
    delay: 3
    period: 3
mysql:
    mysqlPassword: developer_password
    mysqlUser: developer
    mysqlDatabase: otus
    mysqlHost: otus-mysql