apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
type: Opaque
stringData:
  otus_database: server={{.Values.mysql.mysqlHost}};port=3306;user={{.Values.mysql.mysqlUser}};password={{.Values.mysql.mysqlPassword}};database={{.Values.mysql.mysqlDatabase}}