# Default values for otus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: otus
mysql:
    mysqlPassword: developer_password
    mysqlUser: developer
    mysqlDatabase: otus
    mysqlHost: otus-mysql