apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  labels:
    app: mysqld-exporter
spec:
  selector: 
    app: mysqld-exporter
  type: ClusterIP  
  ports:
    - name: http-metrics
      port: 9104
