{
 "title": "otus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Pod",
    "query": "label_values({ instance!=\"\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "nginx error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_ingress_controller_requests{service=\"otus\", status=~\"5..\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "nginx quantile 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_ingress_controller_ingress_upstream_latency_seconds{service=\"otus\", quantile=\"0.99\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "nginx quantile 0.9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_ingress_controller_ingress_upstream_latency_seconds{service=\"otus\", quantile=\"0.9\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "nginx quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_ingress_controller_ingress_upstream_latency_seconds{service=\"otus\", quantile=\"0.5\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aspnetcore_requests_failed_total",
     "legendFormat": "otus"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aspnetcore_requests_per_second", "legendFormat": "otus" }
   ]
  },
  {
   "title": "otus quantile 0.99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "otus quantile 0.95",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "otus quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=\"otus-846bf874cd-qcbqq\", image!~\".*pause.*\",name!=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{pod=\"$Pod\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}